version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: prefect_postgres
    restart: always
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    ports:
      - "5432:5432"
    volumes:
      - prefect-db:/var/lib/postgresql/data


  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    restart: always
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000
    volumes:
      - ./mlruns:/mlflow/artifacts
      - ./mlflow.db:/mlflow.db


  prefect:
    image: prefecthq/prefect:2.16.7-python3.12
    container_name: prefect_server
    command: >
      prefect server start
      --host 0.0.0.0
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
    ports:
      - "4200:4200"
    depends_on:
      - postgres


  prefect-worker:
    image: prefecthq/prefect:2.16.7-python3.12
    container_name: prefect_worker
    command: prefect worker start --pool default-agent-pool
    environment:
      PREFECT_API_URL: http://prefect:4200/api
    depends_on:
      - prefect


  ml_ops_app:
    build: .
    container_name: energy_mlops_container
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      PREFECT_API_URL: http://prefect:4200/api
    depends_on:
      - mlflow
      - prefect
    stdin_open: true
    tty: true


volumes:
  prefect-db:
